name: Cypress Tests

on: push 

jobs:
  install:
    runs-on: ubuntu-24.04 
    steps:
      - name: Checkout 
        uses: actions/checkout@v4 

      - name: Cypress install 
        uses: cypress-io/github-action@v6
        with:
          runTests: false 
          build: npm run build
          working-directory: ./any-chat 
          project: ./any-chat

      - name: Save build folder 
        uses: actions/upload-artifact@v4 
        with:
          name: dist 
          if-no-files-found: error 
          path: ./any-chat/dist 

  cypress-run:
    runs-on: ubuntu-24.04 
    needs: install 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folder 
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./any-chat/dist 

      - name: Cypress run 
        uses: cypress-io/github-action@v6 
        with:
          start: npm run preview 
          browser: chrome 
          record: true
        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

        
