name: Cypress Tests

on: push 

env:
  CYPRESS_BASE_URL: http://localhost:5173/

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      
      - name: Yarn Setup 
        uses: DerYeger/yarn-setup-action@v1.0.1
          
          
      - name: Checkout
        uses: actions/checkout@v4 

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false 
          build: yarn build

      - name: Save build folder 
        uses: actions/upload-artifact@v4 
        with:
          name: dist 
          if-no-files-found: error 
          path: dist

  cypress-run:
    runs-on: ubuntu-22.04
    needs: install 
    steps:
      - name: Checkout 
        uses: actions/checkout@v4  

      - run: yarn install --no-save @testmo/testmo-cli

      - run: |
          dlx testmo automation:resources:add-field --name git --type string \
            --value ${GITHUB_SHA:0:7} --resources resources.json
          RUN_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          npx testmo automation:resources:add-link --name build \
            --url $RUN_URL --resources resources.json

      - name: Download build folder 
        uses: actions/download-artifact@v4
        with:
          name: dist 
          path: dist 

      - run: |
          if [[ -z "${TESTMO_URL}" ]]; then
            echo "The TESTMO_URL secret is not defined for this repository"
            exit 1
          fi

          if [[ -z "${TESTMO_TOKEN}" ]]; then
            echo "The TESTMO_TOKEN secret is not defined for this repository"
            exit 1
          fi
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}

      - run: |
          dlx testmo automation:run:submit \
            --instance "$TESTMO_URL" \
            --project-id 1 \
            --name "Mocha test run" \
            --source "unit-tests" \
            --resources resources.json \
            --results results/*.xml \
            -- yarn cy:test
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}

