name: Cypress Tests

on: push 

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3

      
      - name: Yarn Setup 
        uses: DerYeger/yarn-setup-action@v1.0.1
          
          
      - name: Checkout
        uses: actions/checkout@v4 

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false 
          build: yarn build

      - name: Save build folder 
        uses: actions/upload-artifact@v4 
        with:
          name: dist 
          if-no-files-found: error 
          path: dist

  cypress-run:
    runs-on: ubuntu-22.04
    needs: install 
    steps:
      - name: Checkout 
        uses: actions/checkout@v4 

      - name: Download build folder 
        uses: actions/download-artifact@v4
        with:
          name: dist 
          path: dist 

      - name: Cypress run 
        uses: cypress-io/github-action@v6 
        with:
          start: yarn cy:test
          browser: chrome
